### ISSUE TITLE
This project still active?

### ISSUE THREAD

**Issue by musselmandev** [xemwebe/gurufocus_api#1]
I am confused as when I try to run the examples all I seem to get are unit test results.

**Comment by xemwebe** [comment]
Here is an example of how you could run an example:
```
cargo run --example 02_financials
```

Unfortunately, the gurufocus API changes frequently, therefore the methods break from time to time, as like now.  I will have a look and try to update to the current API.

**Comment by xemwebe** [comment]
Closed since there is no issue to be discussed

**Comment by xemwebe** [comment]
I have just checked: currently three of the 29 unit tests fail. I will try to fix them over the weekend.

**Comment by xemwebe** [comment]
I fixed the three failing test cases and added as bonus request for politician transactions.
